//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosegur.LV.SOL.Dashboard.DAO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Consultas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consultas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosegur.LV.SOL.Dashboard.DAO.Consultas", typeof(Consultas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	JMS_ID,
        ///	ID,
        ///	MENSAJE,
        ///	OBSERVACION,
        ///	ESTADO, 
        ///	ATRIBUTO1, 
        ///	ATRIBUTO2, 
        ///	INTEGRACION,
        ///	DELEGACION
        ///FROM SOL_JMS_ENVIO s
        ///   WHERE     TRUNC (f_alta) &gt;= TRUNC(:FEC_ALTA) AND TRUNC(f_alta) &lt; trunc(:FEC_ALTA) + 2
        ///         AND operacion = &apos;M&apos;
        ///         AND integracion =&apos;RUTA&apos;
        ///         and delegacion in(:DELEGACION)
        ///         AND ESTADO IN (&apos;PE&apos;,&apos;ER&apos;,&apos;OK&apos;)
        ///         AND atributo2 IN (&apos;6&apos;,&apos;7&apos;) -- estado FINALIZADA, estado CERRADA (graba los documentos de SOL en SigII) 
        ///ORDER BY delegacion,
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string JMSGetMensajeCierreFactPorDelegacion {
            get {
                return ResourceManager.GetString("JMSGetMensajeCierreFactPorDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Jms_Id AS JmsId FROM SOL_JMS_ENVIO 
        ///WHERE 
        ///	DELEGACION IN (:DELEGACION) 
        ///    AND INTEGRACION = :INTEGRACION
        ///    AND ESTADO IN (:ESTADO)
        ///	AND ID IN (:ID)
        ///	AND OPERACION = :OPERACION
        ///	AND TRUNC(F_ALTA) &gt; TRUNC(SYSDATE - 5).
        /// </summary>
        internal static string JMSGetMensajePorDelegacionIntegracionEstadoIdOperacion {
            get {
                return ResourceManager.GetString("JMSGetMensajePorDelegacionIntegracionEstadoIdOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Jms_Id AS JmsId, Estado FROM SOL_JMS_ENVIO 
        ///WHERE F_ALTA &gt; SYSDATE - :DESDE_HORAS/24 
        ///    AND DELEGACION IN (:DELEGACION) 
        ///    AND INTEGRACION = :INTEGRACION
        ///    AND ESTADO = :ESTADO.
        /// </summary>
        internal static string JMSGetMensajePorHorasDelegacionIntegracionEstado {
            get {
                return ResourceManager.GetString("JMSGetMensajePorHorasDelegacionIntegracionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	J1.ID,
        ///	J1.MENSAJE,
        ///	J1.OBSERVACION,
        ///	J1.ESTADO, 
        ///	J1.ATRIBUTO1, 
        ///	J1.ATRIBUTO2, 
        ///	J1.INTEGRACION,
        ///	J1.DELEGACION
        ///FROM SOL_JMS_ENVIO J1
        ///WHERE 
        ///	J1.JMS_ID IN (:JMS_ID )
        ///.
        /// </summary>
        internal static string JMSGetMensajePorJmsId {
            get {
                return ResourceManager.GetString("JMSGetMensajePorJmsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT J1.ID, J1.MENSAJE, J1.OBSERVACION, J1.DELEGACION, J1.ESTADO FROM SOL_JMS_ENVIO J1 
        ///WHERE J1.F_ALTA &gt; SYSDATE - :DESDE_HORAS/24 AND J1.DELEGACION IN (:DELEGACION) 
        ///      AND J1.INTEGRACION = :INTEGRACION AND J1.ESTADO = :ESTADO
        ///      AND NOT EXISTS (SELECT 1 FROM SOL_JMS_ENVIO J2 
        ///                      WHERE J2.F_ALTA &gt; J1.F_ALTA 
        ///                            AND J2.DELEGACION = J1.DELEGACION AND J2.ID = J1.ID 
        ///                            AND J2.INTEGRACION = J1.INTEGRACION AND J2.ESTADO &lt;&gt; J1.ES [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string JMSGetUltimoMensajeErrorPorHorasDelegacionIntegracion {
            get {
                return ResourceManager.GetString("JMSGetUltimoMensajeErrorPorHorasDelegacionIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM ( 
        ///	SELECT ESTADO, JMS_ID AS JmsId, DELEGACION FROM SOL_JMS_ENVIO 
        ///	WHERE 
        ///		INTEGRACION = :INTEGRACION 
        ///		AND ATRIBUTO1 = :ATRIBUTO1
        ///		AND ID = :ID
        ///		AND OPERACION = :OPERACION 
        ///		AND DELEGACION = :DELEGACION 
        ///	ORDER BY JMS_ID DESC) 
        ///WHERE ROWNUM &lt;= 1 .
        /// </summary>
        internal static string JMSGetUltimoMensajePorAtributo1IntegracionIdOperacionDelegacion {
            get {
                return ResourceManager.GetString("JMSGetUltimoMensajePorAtributo1IntegracionIdOperacionDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM ( 
        ///	SELECT ESTADO, JMS_ID AS JmsId FROM SOL_JMS_ENVIO 
        ///	WHERE 
        ///		INTEGRACION = :INTEGRACION 
        ///		AND ATRIBUTO2 = :ATRIBUTO2
        ///		AND OPERACION = :OPERACION 
        ///		AND DELEGACION = :DELEGACION 
        ///	ORDER BY JMS_ID DESC) 
        ///WHERE ROWNUM &lt;= 1 .
        /// </summary>
        internal static string JMSGetUltimoMensajePorAtributo2IntegracionOperacionDelegacion {
            get {
                return ResourceManager.GetString("JMSGetUltimoMensajePorAtributo2IntegracionOperacionDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM ( 
        ///	SELECT ESTADO, JMS_ID AS JmsId, DELEGACION FROM SOL_JMS_ENVIO 
        ///	WHERE 
        ///		INTEGRACION = :INTEGRACION 
        ///		AND ATRIBUTO2 = :ATRIBUTO2
        ///		AND OPERACION = :OPERACION 
        ///		AND DELEGACION = :DELEGACION 
        ///		AND ESTADO IN (:ESTADO)
        ///		AND TRUNC(F_ALTA) &gt;= TRUNC(SYSDATE - 5)
        ///	ORDER BY JMS_ID DESC) 
        ///WHERE ROWNUM &lt;= 1 .
        /// </summary>
        internal static string JMSGetUltimoMensajePorAtributo2IntegracionOperacionDelegacionEstado {
            get {
                return ResourceManager.GetString("JMSGetUltimoMensajePorAtributo2IntegracionOperacionDelegacionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM ( 
        ///	SELECT ESTADO, JMS_ID AS JmsId, DELEGACION FROM SOL_JMS_ENVIO 
        ///	WHERE 
        ///		INTEGRACION = :INTEGRACION 
        ///		AND ATRIBUTO1 = :ATRIBUTO1
        ///		AND ATRIBUTO2 = :ATRIBUTO2
        ///		AND OPERACION = :OPERACION 
        ///		AND DELEGACION = :DELEGACION
        ///		AND ESTADO IN (:ESTADO)
        ///		AND TRUNC(F_ALTA) &gt;= TRUNC(SYSDATE - 5)
        ///	ORDER BY JMS_ID DESC) 
        ///WHERE ROWNUM &lt;= 1 .
        /// </summary>
        internal static string JMSGetUltimoMensajePorAtributoIntegracionOperacionDelegacionEstado {
            get {
                return ResourceManager.GetString("JMSGetUltimoMensajePorAtributoIntegracionOperacionDelegacionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	P.DELEGACION AS CodigoDelegacion, 
        ///	G.GRUPO AS CodigoGrupo
        ///FROM SOL_PERSONA_GRUPO G INNER JOIN SOL_PLANTA P ON G.EMPRESA = P.EMPRESA AND G.PLANTA = P.PLANTA 
        ///WHERE P.EMPRESA = 1 AND G.F_SERVICIO = @F_SERVICIO 
        ///	AND P.DELEGACION IN (@DELEGACION)
        ///	AND G.GRUPO IN (@GRUPO)
        ///GROUP BY P.DELEGACION, G.GRUPO .
        /// </summary>
        internal static string SIGIIGetEstadoProgramacionGrupoPorFechaGrupo {
            get {
                return ResourceManager.GetString("SIGIIGetEstadoProgramacionGrupoPorFechaGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	SR.RECORRIDO AS CodigoRecorrido, 
        ///	SR.CIERRE_SERVICIOS AS CierreServicios,
        ///	SR.CIERRE_RECURSOS AS CierreRecursos
        ///FROM SOL_RUTA SR 
        ///WHERE 
        ///	SR.EMPRESA = 1 
        ///	AND SR.F_SERVICIO = @F_SERVICIO
        ///	AND SR.RECORRIDO IN (@RECORRIDO)
        ///.
        /// </summary>
        internal static string SIGIIGetEstadoProgramacionRecorridoPorFechaRecorrido {
            get {
                return ResourceManager.GetString("SIGIIGetEstadoProgramacionRecorridoPorFechaRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	SP.DELEGACION AS CodigoDelegacion,
        ///	PR.F_SERVICIO AS FechaCierreRecurso
        ///FROM SOL_PLANTA SP 
        ///  LEFT JOIN PRP_HORA_FIN_PROG PR ON SP.PLANTA = PR.PLANTA AND SP.EMPRESA = PR.EMPRESA 
        ///  AND PR.F_SERVICIO = @F_SERVICIO
        ///  AND PR.ESTADO = &apos;C&apos;
        ///WHERE 
        /// SP.EMPRESA = 1 
        /// AND SP.DELEGACION IN (@DELEGACION)
        /// 
        ///.
        /// </summary>
        internal static string SIGIIGetFechaProgramacionRecursoPorFechaDelegacion {
            get {
                return ResourceManager.GetString("SIGIIGetFechaProgramacionRecursoPorFechaDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///	S.DELEGACION AS CodigoDelegacion,
        ///	F.FECHA_PROCESO AS FechaCierreServicio
        ///FROM SOL_PLANTA S
        ///  INNER JOIN PLANTAS P ON P.EMPRESA = S.EMPRESA AND P.PLANTA = S.PLANTA
        ///  LEFT OUTER JOIN REP_PRE_HOJA_RUTA_GENERACION_PRG F ON  F.PLANTA = P.PLANTA AND F.FECHA_PROCESO = @F_SERVICIO
        ///WHERE S.EMPRESA = 1
        ///  AND S.DELEGACION IN (@DELEGACION)
        ///ORDER BY S.DELEGACION
        ///.
        /// </summary>
        internal static string SIGIIGetFechaProgramacionServicioPorFechaDelegacion {
            get {
                return ResourceManager.GetString("SIGIIGetFechaProgramacionServicioPorFechaDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	HO.OID_OT AS OidOT, 
        ///	HO.CONTROL, 
        ///	H.FECHA_PROCESO AS FechaProceso, 
        ///	H.H_SERVICIO AS HoraProceso, 
        ///	H.RECORRIDO 
        ///FROM HOJA_RUTA H 
        ///LEFT JOIN SOL_HOJARUTA_OT HO ON H.CONTROL = HO.CONTROL AND H.F_SERVICIO = HO.F_SERVICIO AND H.EMPRESA = HO.EMPRESA 
        ///WHERE 
        ///	HO.EMPRESA = 1 AND 
        ///	H.RECORRIDO IN (@RECORRIDO) AND 
        ///	H.ESTADO &lt;&gt; &apos;B&apos; AND 
        ///	H.TIPO_SERVICIO &lt;&gt; 10 AND 
        ///	NOT (H.FAMILIA = &apos;Z&apos; AND H.SERVICIO IN (9998, 9997)) AND 
        ///	H.F_SERVICIO  = @F_SERVICIO.
        /// </summary>
        internal static string SIGIIGetHojaDeRutaPorRecorridoFechaDeServicio {
            get {
                return ResourceManager.GetString("SIGIIGetHojaDeRutaPorRecorridoFechaDeServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	P.PLANTA AS CODIGO, 
        ///	P.DESCRIPCION, 
        ///	S.DELEGACION, 
        ///	R.RECORRIDO, 
        ///	R.OBSERVACION  
        ///FROM PLANTAS P
        ///	INNER JOIN SOL_PLANTA S ON P.EMPRESA = S.EMPRESA AND P.PLANTA = S.PLANTA
        ///	LEFT JOIN RECORRIDO R ON P.EMPRESA = R.EMPRESA AND P.RECO_REP = R.RECORRIDO
        ///WHERE S.DELEGACION IN (@DELEGACION) AND S.EMPRESA = 1.
        /// </summary>
        internal static string SIGIIGetPlantaConRecorridoBasureroPorDelegacion {
            get {
                return ResourceManager.GetString("SIGIIGetPlantaConRecorridoBasureroPorDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SET LOCK MODE TO WAIT;.
        /// </summary>
        internal static string SIGIILockMode {
            get {
                return ResourceManager.GetString("SIGIILockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select b.DELEGACION as Delegacion,
        ///	   a.RECORRIDO as Recorrido,
        ///	   a.REVISION as Revision from sol_ruta a
        ///	   join sol_planta b on 
        ///    a.empresa = b.empresa and
        ///	a.planta =b.planta
        ///where a.empresa = 1 
        ///	and f_servicio = @F_SERVICIO
        ///	and b.delegacion IN (@DELEGACION).
        /// </summary>
        internal static string SIGIISol_Ruta {
            get {
                return ResourceManager.GetString("SIGIISol_Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	O.OID_OT AS OidOT, 
        ///	S.COD_SERVICIO AS CodigoServicio, 
        ///	O.COD_SECUENCIA AS CodigoSecuencia, 
        ///	R.COD_RUTA AS CodigoRuta, 
        ///	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio
        ///FROM SLDL_TOT O 
        ///	LEFT JOIN SLDL_TSERVICIO S ON O.OID_SERVICIO = S.OID_SERVICIO 
        ///	LEFT JOIN SLDL_TPARADA P ON O.OID_PARADA = P.OID_PARADA 
        ///	LEFT JOIN SLDL_TRUTA R ON P.OID_RUTA = R.OID_RUTA 
        ///WHERE 
        ///	O.OID_OT IN (:OID_OT) .
        /// </summary>
        internal static string SOLGetDetalleOrdenDeTrabajo {
            get {
                return ResourceManager.GetString("SOLGetDetalleOrdenDeTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///	D.DES_DELEGACION AS DescripcionDelegacion,
        ///	D.COD_DELEGACION AS CodigoDelegacion, 
        ///	R.COD_RUTA AS CodigoRuta, 
        ///	R.OID_RUTA AS OidRuta, 
        ///	R.FYH_CIERRE_PROGRAMA_RECURSO AS FechaCierreRecurso,
        ///	R.FYH_CIERRE_PROGRAMA_SERVICIO AS FechaCierreServicio
        ///FROM SLDG_TDELEGACION D INNER JOIN SLDL_TRUTA R 
        ///	ON  R.OID_DELEGACION = D.OID_DELEGACION 
        ///WHERE R.FEC_RUTA = TRUNC(:FEC_RUTA) 
        ///	AND D.COD_DELEGACION IN (:COD_DELEGACION) 
        ///.
        /// </summary>
        internal static string SOLGetEstadoProgramacionRutaPorFechaDelegacion {
            get {
                return ResourceManager.GetString("SOLGetEstadoProgramacionRutaPorFechaDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	D.COD_DELEGACION AS CodigoDelegacion,
        ///	D.DES_DELEGACION AS DescripcionDelegacion,
        ///	S.COD_SECTOR AS CodigoSector,
        ///	SC.FEC_CIERRE AS FechaCierre, 
        ///	COUNT(PXS.OID_PERSONA) AS CantidadRecursos
        ///FROM SLDL_TSECTOR S 
        ///	INNER JOIN SLDG_TDELEGACION D ON S.OID_DELEGACION = D.OID_DELEGACION 
        ///	LEFT JOIN SLDL_TSECTOR_CIERRE SC ON S.OID_SECTOR = SC.OID_SECTOR AND SC.FEC_CIERRE = TRUNC(:FEC_CIERRE) 
        ///	LEFT JOIN SLDL_TPERSONAXSECTOR PXS ON S.OID_SECTOR = PXS.OID_SECTOR AND TRUNC(FYH_PROGRAMACION_INICIO) = S [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SOLGetEstadoProgramacionSectorPorFechaDelegacion {
            get {
                return ResourceManager.GetString("SOLGetEstadoProgramacionSectorPorFechaDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	D.COD_DELEGACION AS CodigoDelegacion,
        ///	D.DES_DELEGACION AS DescripcionDelegacion,
        ///	P.FYH_CIERRE_PROG_SERVICIO AS FechaCierreServicio, 
        ///	P.FYH_CIERRE_PROG_RECURSO AS FechaCierreRecurso
        ///FROM SLDG_TDELEGACION D LEFT OUTER JOIN SLDL_TCIERRE_PROGRAMACION P  
        ///								 ON D.OID_DELEGACION = P.OID_DELEGACION 
        ///								 AND TRUNC(P.FEC_PROGRAMACION) = TRUNC(:FEC_PROGRAMACION) 
        ///WHERE COD_DELEGACION IN (:COD_DELEGACION) 
        ///.
        /// </summary>
        internal static string SOLGetFechasProgramacionPorFechaDelegacion {
            get {
                return ResourceManager.GetString("SOLGetFechasProgramacionPorFechaDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	R.COD_RUTA AS CodigoRuta, 
        ///	R.OID_RUTA AS OidRuta,
        ///	O.OID_OT AS OidOt, 
        ///	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio,
        ///	D.COD_DELEGACION AS CodigoDelegacion
        ///FROM SLDL_TRUTA R  
        ///	INNER JOIN SLDL_TPARADA P ON P.OID_RUTA = R.OID_RUTA 
        ///	INNER JOIN SLDL_TOT O ON P.OID_PARADA = O.OID_PARADA 
        ///	INNER JOIN SLDG_TDELEGACION D ON D.OID_DELEGACION = R.OID_DELEGACION 
        ///WHERE 
        ///	O.OID_SERVICIO IS NOT NULL 
        ///	AND D.COD_DELEGACION IN (:DELEGACION) 
        ///	AND R.FEC_RUTA = TRUNC(:FEC_RUTA)
        ///	AND R.COD_RUTA  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SOLGetOrdenDeTrabajoAIntegrarPorFechaServicioDelegacion {
            get {
                return ResourceManager.GetString("SOLGetOrdenDeTrabajoAIntegrarPorFechaServicioDelegacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	R.COD_RUTA AS CodigoRuta, 
        ///	O.OID_OT AS OidOt, 
        ///	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio,
        ///	D.COD_DELEGACION AS CodigoDelegacion,
        ///	S.COD_SERVICIO AS CodigoServicio,
        ///	O.COD_SECUENCIA AS CodigoSecuencia
        ///FROM SLDL_TRUTA R  
        ///	INNER JOIN SLDL_TPARADA P ON P.OID_RUTA = R.OID_RUTA 
        ///	INNER JOIN SLDL_TOT O ON P.OID_PARADA = O.OID_PARADA 
        ///	LEFT JOIN SLDL_TSERVICIO S ON O.OID_SERVICIO = S.OID_SERVICIO 
        ///	INNER JOIN SLDG_TDELEGACION D ON D.OID_DELEGACION = R.OID_DELEGACION 
        ///WHERE 
        ///	O.OID_SE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SOLGetOrdenDeTrabajoAIntegrarPorFechaServicioRuta {
            get {
                return ResourceManager.GetString("SOLGetOrdenDeTrabajoAIntegrarPorFechaServicioRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	U.OID_USUARIO AS Oid,
        ///    U.DES_NOMBRE AS Nombre
        ///FROM SLDG_TUSUARIO U
        ///WHERE 
        ///	 LOWER(U.DES_LOGIN) = :DES_LOGIN AND 
        ///	 U.BOL_ACTIVO = 1.
        /// </summary>
        internal static string SOLGetUsuario {
            get {
                return ResourceManager.GetString("SOLGetUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	U.OID_USUARIO AS Oid,
        ///    U.DES_NOMBRE AS Nombre,
        ///	R.OID_ROL AS OidRol,
        ///	R.COD_ROL AS CodigoRol,
        ///	R.DES_ROL AS DescripcionRol
        ///FROM SLDG_TUSUARIO U 
        ///LEFT JOIN SLDG_TROLXUSUARIO UR ON U.OID_USUARIO = UR.OID_USUARIO
        ///LEFT JOIN SLDG_TROL R ON R.OID_ROL = UR.OID_ROL 
        ///WHERE 
        ///	 LOWER(U.DES_LOGIN) = :DES_LOGIN AND 
        ///	 U.BOL_ACTIVO = 1.
        /// </summary>
        internal static string SOLGetUsuarioConRoles {
            get {
                return ResourceManager.GetString("SOLGetUsuarioConRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	D.COD_DELEGACION AS Codigo,
        ///	D.DES_DELEGACION AS Descripcion
        ///FROM SLDG_TUSUARIO U 
        ///	INNER JOIN SLDG_TUSUARIOXDELEGACION UD ON U.OID_USUARIO = UD.OID_USUARIO 
        ///	INNER JOIN SLDG_TDELEGACION D ON UD.OID_DELEGACION = D.OID_DELEGACION 
        ///WHERE 
        ///	U.OID_USUARIO = :OID_USUARIO
        ///ORDER BY D.DES_DELEGACION ASC.
        /// </summary>
        internal static string SOLGetUsuarioDelegaciones {
            get {
                return ResourceManager.GetString("SOLGetUsuarioDelegaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT RUT.OID_RUTA AS OidRuta,
        ///         DELE.COD_DELEGACION AS CodigoDelegacion,
        ///         RUT.COD_RUTA AS CodigoRuta,
        ///         RUT.COD_ESTADO AS CodigoEstado
        ///    FROM SLDL_TRUTA RUT
        ///         JOIN SLDG_TDELEGACION DELE ON RUT.OID_DELEGACION = DELE.OID_DELEGACION
        ///   WHERE     RUT.COD_ESTADO IN (6, 7)
        ///         AND RUT.FEC_RUTA = TRUNC ( :FEC_RUTA)
        ///         AND DELE.COD_DELEGACION IN ( :DELEGACIONES)
        ///ORDER BY 1, 2, 3.
        /// </summary>
        internal static string SOLRutasFinalizadasCerradas {
            get {
                return ResourceManager.GetString("SOLRutasFinalizadasCerradas", resourceCulture);
            }
        }
    }
}
