SELECT 
	J1.ID,
	J1.MENSAJE,
	J1.OBSERVACION,
	J1.ESTADO, 
	J1.ATRIBUTO1, 
	J1.ATRIBUTO2, 
	J1.INTEGRACION,
	J1.DELEGACION,
    SUBSTR( j1.atributo1,INSTR( j1.atributo1, '|', -1 ) + 1 )  as Cod_ruta
FROM SOL_JMS_ENVIO J1
WHERE 
	J1.JMS_ID IN (:JMS_ID )
