SELECT Jms_Id AS JmsId FROM SOL_JMS_ENVIO 
WHERE 
	DELEGACION IN (:DELEGACION) 
    AND INTEGRACION = :INTEGRACION
    AND ESTADO IN (:ESTADO)
	AND ID IN (:ID)
	AND OPERACION = :OPERACION
	AND TRUNC(F_ALTA) > TRUNC(SYSDATE - 5)