SELECT * FROM ( 
	SELECT ESTADO, JMS_ID AS JmsId, DELEGACION FROM SOL_JMS_ENVIO 
	WHERE 
		INTEGRACION = :INTEGRACION 
		AND ATRIBUTO1 = :ATRIBUTO1
		AND ID = :ID
		AND OPERACION = :OPERACION 
		AND DELEGACION = :DELEGACION 
	ORDER BY JMS_ID DESC) 
WHERE ROWNUM <= 1 