SELECT 
	J1.ID,
	J1.MENSAJE,
	J1.OBSERVACION,
	J1.ESTADO, 
	J1.ATRIBUTO1, 
	J1.ATRIBUTO2, 
	J1.INTEGRACION,
	J1.DELEGACION,
    RUT.COD_RUTA
FROM SOL_JMS_ENVIO J1
LEFT JOIN SLDL_TRUTA RUT ON RUT.OID_RUTA = J1.ID
WHERE 
	J1.JMS_ID IN (:JMS_ID )
