SELECT J1.ID, J1.MENSAJE, J1.OBSERVACION, J1.DELEGACION, J1.ESTADO FROM SOL_JMS_ENVIO J1 
WHERE J1.F_ALTA > SYSDATE - :DESDE_HORAS/24 AND J1.DELEGACION IN (:DELEGACION) 
      AND J1.INTEGRACION = :INTEGRACION AND J1.ESTADO = :ESTADO
      AND NOT EXISTS (SELECT 1 FROM SOL_JMS_ENVIO J2 
                      WHERE J2.F_ALTA > J1.F_ALTA 
                            AND J2.DELEGACION = J1.DELEGACION AND J2.ID = J1.ID 
                            AND J2.INTEGRACION = J1.INTEGRACION AND J2.ESTADO <> J1.ESTADO)