SELECT * FROM ( 
	SELECT ESTADO, JMS_ID AS JmsId FROM SOL_JMS_ENVIO 
	WHERE 
		INTEGRACION = :INTEGRACION 
		AND ATRIBUTO2 = :ATRIBUTO2
		AND OPERACION = :OPERACION 
		AND DELEGACION = :DELEGACION 
	ORDER BY JMS_ID DESC) 
WHERE ROWNUM <= 1 