SELECT 
	HO.OID_OT AS OidOT, 
	HO.CONTROL, 
	H.FECHA_PROCESO AS FechaProceso, 
	H.H_SERVICIO AS HoraProceso, 
	H.RECORRIDO 
FROM HOJA_RUTA H 
LEFT JOIN SOL_HOJARUTA_OT HO ON H.CONTROL = HO.CONTROL AND H.F_SERVICIO = HO.F_SERVICIO AND H.EMPRESA = HO.EMPRESA 
WHERE 
	HO.EMPRESA = 1 AND 
	H.RECORRIDO IN (@RECORRIDO) AND 
	H.ESTADO <> 'B' AND 
	H.TIPO_SERVICIO <> 10 AND 
	NOT (H.FAMILIA = 'Z' AND H.SERVICIO IN (9998, 9997)) AND 
	H.F_SERVICIO  = @F_SERVICIO