SELECT 
	SR.RECORRIDO AS CodigoRecorrido, 
	SR.CIERRE_SERVICIOS AS CierreServicios,
	SR.CIERRE_RECURSOS AS CierreRecursos
FROM SOL_RUTA SR 
WHERE 
	SR.EMPRESA = 1 
	AND SR.F_SERVICIO = @F_SERVICIO
	AND SR.RECORRIDO IN (@RECORRIDO)
