SELECT 
	P.DELEGACION AS CodigoDelegacion, 
	G.GRUPO AS CodigoGrupo
FROM SOL_PERSONA_GRUPO G INNER JOIN SOL_PLANTA P ON G.EMPRESA = P.EMPRESA AND G.PLANTA = P.PLANTA 
WHERE P.EMPRESA = 1 AND G.F_SERVICIO = @F_SERVICIO 
	AND P.DELEGACION IN (@DELEGACION)
	AND G.GRUPO IN (@GRUPO)
GROUP BY P.DELEGACION, G.GRUPO 