SELECT
	S.DELEGACION AS CodigoDelegacion,
	F.FECHA_PROCESO AS FechaCierreServicio
FROM SOL_PLANTA S
  INNER JOIN PLANTAS P ON P.EMPRESA = S.EMPRESA AND P.PLANTA = S.PLANTA
  LEFT OUTER JOIN REP_PRE_HOJA_RUTA_GENERACION_PRG F ON  F.PLANTA = P.PLANTA AND F.FECHA_PROCESO = @F_SERVICIO
WHERE S.EMPRESA = 1
  AND S.DELEGACION IN (@DELEGACION)
ORDER BY S.DELEGACION
