SELECT 
	P.PLANTA AS CODIGO, 
	P.DESCRIPCION, 
	S.DELEGACION, 
	R.RECORRIDO, 
	R.OBSERVACION  
FROM PLANTAS P
	INNER JOIN SOL_PLANTA S ON P.EMPRESA = S.EMPRESA AND P.PLANTA = S.PLANTA
	LEFT JOIN RECORRIDO R ON P.EMPRESA = R.EMPRESA AND P.RECO_REP = R.RECORRIDO
WHERE S.DELEGACION IN (@DELEGACION) AND S.EMPRESA = 1