SELECT 
	SP.DELEGACION AS CodigoDelegacion,
	PR.F_SERVICIO AS FechaCierreRecurso
FROM SOL_PLANTA SP 
  LEFT JOIN PRP_HORA_FIN_PROG PR ON SP.PLANTA = PR.PLANTA AND SP.EMPRESA = PR.EMPRESA 
  AND PR.F_SERVICIO = @F_SERVICIO
  AND PR.ESTADO = 'C'
WHERE 
 SP.EMPRESA = 1 
 AND SP.DELEGACION IN (@DELEGACION)
 
