SELECT 
	R.COD_RUTA AS CodigoRuta, 
	O.OID_OT AS OidOt, 
	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio,
	D.COD_DELEGACION AS CodigoDelegacion,
	S.COD_SERVICIO AS CodigoServicio,
	O.COD_SECUENCIA AS CodigoSecuencia
FROM SLDL_TRUTA R  
	INNER JOIN SLDL_TPARADA P ON P.OID_RUTA = R.OID_RUTA 
	INNER JOIN SLDL_TOT O ON P.OID_PARADA = O.OID_PARADA 
	LEFT JOIN SLDL_TSERVICIO S ON O.OID_SERVICIO = S.OID_SERVICIO 
	INNER JOIN SLDG_TDELEGACION D ON D.OID_DELEGACION = R.OID_DELEGACION 
WHERE 
	O.OID_SERVICIO IS NOT NULL 
	AND TRUNC(R.FEC_RUTA) = TRUNC(:FEC_RUTA)
	AND R.COD_RUTA IN (:COD_RUTA)
	AND NOT O.COD_ESTADO IN (1, 11)