SELECT 
	D.COD_DELEGACION AS CodigoDelegacion,
	D.DES_DELEGACION AS DescripcionDelegacion,
	S.COD_SECTOR AS CodigoSector,
	SC.FEC_CIERRE AS FechaCierre, 
	COUNT(PXS.OID_PERSONA) AS CantidadRecursos
FROM SLDL_TSECTOR S 
	INNER JOIN SLDG_TDELEGACION D ON S.OID_DELEGACION = D.OID_DELEGACION 
	LEFT JOIN SLDL_TSECTOR_CIERRE SC ON S.OID_SECTOR = SC.OID_SECTOR AND SC.FEC_CIERRE = TRUNC(:FEC_CIERRE) 
	LEFT JOIN SLDL_TPERSONAXSECTOR PXS ON S.OID_SECTOR = PXS.OID_SECTOR AND TRUNC(FYH_PROGRAMACION_INICIO) = SC.FEC_CIERRE 
WHERE D.COD_DELEGACION IN (:COD_DELEGACION) 
GROUP BY D.COD_DELEGACION, D.DES_DELEGACION, S.COD_SECTOR, SC.FEC_CIERRE 
                            