SELECT 
	R.COD_RUTA AS CodigoRuta, 
	R.OID_RUTA AS OidRuta,
	O.OID_OT AS OidOt, 
	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio,
	D.COD_DELEGACION AS CodigoDelegacion
FROM SLDL_TRUTA R  
	INNER JOIN SLDL_TPARADA P ON P.OID_RUTA = R.OID_RUTA 
	INNER JOIN SLDL_TOT O ON P.OID_PARADA = O.OID_PARADA 
	INNER JOIN SLDG_TDELEGACION D ON D.OID_DELEGACION = R.OID_DELEGACION 
WHERE 
	O.OID_SERVICIO IS NOT NULL 
	AND D.COD_DELEGACION IN (:DELEGACION) 
	AND R.FEC_RUTA = TRUNC(:FEC_RUTA)
	AND R.COD_RUTA NOT IN (:COD_RUTA_BASURERO)
	AND NOT O.COD_ESTADO IN (1, 11)