SELECT 
	D.COD_DELEGACION AS Codigo,
	D.DES_DELEGACION AS Descripcion
FROM SLDG_TUSUARIO U 
	INNER JOIN SLDG_TUSUARIOXDELEGACION UD ON U.OID_USUARIO = UD.OID_USUARIO 
	INNER JOIN SLDG_TDELEGACION D ON UD.OID_DELEGACION = D.OID_DELEGACION 
WHERE 
	U.OID_USUARIO = :OID_USUARIO
ORDER BY D.DES_DELEGACION ASC