SELECT 
	D.COD_DELEGACION AS CodigoDelegacion,
	D.DES_DELEGACION AS DescripcionDelegacion,
	P.FYH_CIERRE_PROG_SERVICIO AS FechaCierreServicio, 
	P.FYH_CIERRE_PROG_RECURSO AS FechaCierreRecurso
FROM SLDG_TDELEGACION D LEFT OUTER JOIN SLDL_TCIERRE_PROGRAMACION P  
								 ON D.OID_DELEGACION = P.OID_DELEGACION 
								 AND TRUNC(P.FEC_PROGRAMACION) = TRUNC(:FEC_PROGRAMACION) 
WHERE COD_DELEGACION IN (:COD_DELEGACION) 
