SELECT 
	U.OID_USUARIO AS Oid,
    U.DES_NOMBRE AS Nombre,
	R.OID_ROL AS OidRol,
	R.COD_ROL AS CodigoRol,
	R.DES_ROL AS DescripcionRol
FROM SLDG_TUSUARIO U 
LEFT JOIN SLDG_TROLXUSUARIO UR ON U.OID_USUARIO = UR.OID_USUARIO
LEFT JOIN SLDG_TROL R ON R.OID_ROL = UR.OID_ROL 
WHERE 
	 LOWER(U.DES_LOGIN) = :DES_LOGIN AND 
	 U.BOL_ACTIVO = 1