SELECT
	D.DES_DELEGACION AS DescripcionDelegacion,
	D.COD_DELEGACION AS CodigoDelegacion, 
	R.COD_RUTA AS CodigoRuta, 
	R.OID_RUTA AS OidRuta, 
	R.FYH_CIERRE_PROGRAMA_RECURSO AS FechaCierreRecurso,
	R.FYH_CIERRE_PROGRAMA_SERVICIO AS FechaCierreServicio
FROM SLDG_TDELEGACION D INNER JOIN SLDL_TRUTA R 
	ON  R.OID_DELEGACION = D.OID_DELEGACION 
WHERE R.FEC_RUTA = TRUNC(:FEC_RUTA) 
	AND D.COD_DELEGACION IN (:COD_DELEGACION) 
