SELECT 
	D.COD_DELEGACION,
	D.DES_DELEGACION,
	P.FYH_CIERRE_PROG_SERVICIO,
	P.FYH_CIERRE_PROG_RECURSO
FROM SLDG_TDELEGACION D LEFT OUTER JOIN SLDL_TCIERRE_PROGRAMACION P  
								 ON D.OID_DELEGACION = P.OID_DELEGACION 
								 AND TRUNC(P.FEC_PROGRAMACION) = TRUNC(:FEC_PROGRAMACION) 
WHERE COD_DELEGACION IN (:COD_DELEGACION) 
