SELECT 
	O.OID_OT AS OidOT, 
	S.COD_SERVICIO AS CodigoServicio, 
	O.COD_SECUENCIA AS CodigoSecuencia, 
	R.COD_RUTA AS CodigoRuta, 
	O.FYH_PROGRAMADA_INICIO AS FechaProgramadaInicio
FROM SLDL_TOT O 
	LEFT JOIN SLDL_TSERVICIO S ON O.OID_SERVICIO = S.OID_SERVICIO 
	LEFT JOIN SLDL_TPARADA P ON O.OID_PARADA = P.OID_PARADA 
	LEFT JOIN SLDL_TRUTA R ON P.OID_RUTA = R.OID_RUTA 
WHERE 
	O.OID_OT IN (:OID_OT) 